config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users
  resources :products
  resources :withdrawals
  root 'products#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  content    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  # validates :name, presence: true
  validates :site_url, presence: true
  # validates :content, presence: true
  mount_uploader :image, ProductImageUploader
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  deleted_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_paranoid
  has_many :products
  has_one :withdrawal
  validates :email, uniqueness_without_deleted: true

  # deviseの設定をオーバライドして、emailのユニーク制約だけを外す
  def self.included(base)
    base.extend ClassMethods
    assert_validations_api!(base)

    base.class_eval do
      validates_presence_of   :email, if: :email_required?
      # validates_uniqueness_of :email, allow_blank: true, if: :email_changed?
      validates_format_of     :email, with: email_regexp, allow_blank: true, if: :email_changed?

      validates_presence_of     :password, if: :password_required?
      validates_confirmation_of :password, if: :password_required?
      validates_length_of       :password, within: password_length, allow_blank: true
    end
  end

  # uniqueness_without_deleted: true を追加するとユニークチェックが余分にかかってしまうのを阻止する
  def email_changed?
    false
  end
end

app/models/withdrawal.rb
# == Schema Information
#
# Table name: withdrawals
#
#  id                    :integer          not null, primary key
#  impression_unuseful   :boolean          default(FALSE), not null
#  impression_difficult  :boolean          default(FALSE), not null
#  impression_not_enough :boolean          default(FALSE), not null
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#

class Withdrawal < ActiveRecord::Base
  attr_accessor :impression
  validates :impression, present_impression: true
  has_one :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.joins(:user)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(create_product_params)
    @site_url = @product.site_url
    # @product.title = get_url_title(@site_url)
    # @product.title = get_url_title_by_capybara(@site_url)
    get_url_title_by_capybara(@site_url)

    if @product.save
      redirect_to edit_product_path(@product)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(update_product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def create_product_params
      # params.require(:product).permit(:name, :site_url, :content).merge(user_id: current_user.id)
      params.require(:product).permit(:name, :site_url, :image).merge(user_id: current_user.id)
    end

    def update_product_params
      params.require(:product).permit(:name, :site_url, :title, :content, :image).merge(user_id: current_user.id)
    end

    def get_url_title(url)
      agent = Mechanize.new
      page = agent.get("#{url}")
      element = page.at('head title')
      title = element.inner_text
      # 以下はdescriptionを取得する場合
      # node = page.at("head meta[name='description']")
      # description = node["content"]
    end

    def get_url_title_by_capybara(url)
      Capybara.register_driver :poltergeist do |app|
        Capybara::Poltergeist::Driver.new(app, {:js_errors => false, :timeout => 1000 })
      end
      Capybara.ignore_hidden_elements = false
      session = Capybara::Session.new(:poltergeist)
      session.visit "#{url}"
      title = session.find('head title').text
      @product.title = title
      tmp_description = session.all('meta[name="description"]')
      description = tmp_description[0]
      if description == nil
      else
        @product.content = description['content']
      end
      # img = session.first('img')
      # @product.picture_url = img['src']
      # 以下はfindを使うと例外のエラーが発生するためallを使っている
      tmp_og_image = session.all('meta[property="og:image"]')
      og_image = tmp_og_image[0]
      if og_image == nil
      else
        @product.picture_url = og_image['content']
      end
      session.driver.quit
      Capybara.reset_sessions!
      # 一番最初に出てきたh1のtextを取得
      # session.first('h1').text
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/withdrawals_controller.rb
class WithdrawalsController < ApplicationController

  def new
    @withdrawal = Withdrawal.new
  end

  def create
    @withdrawal = Withdrawal.new(withdrawal_params)
    if @withdrawal.save
      current_user.destroy
    else
      render :new
    end
  end

  private
  def withdrawal_params
    params.require(:withdrawal).permit(:impression_unuseful, :impression_difficult, :impression_not_enough).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def document_title
    if @title.present?
      "#{@title} | Sample2"
    else
      'Sample2'
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/withdrawals_helper.rb
module WithdrawalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- <title><%= document_title %></title> -->
  <title><%= yield :title %> | Sample2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta property="og:description" content="popmacの実験アプリです">
  <meta property="og:image" content="<%= image_url "img_for_SNS.png" %>">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="Sample2">
  <meta name="twitter:description" content="popmacの実験アプリです">
  <meta name="twitter:image" content="https://afternoon-coast-74109.herokuapp.com<%= asset_path "img_for_SNS.png" %>">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= @product.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <!-- <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= @product.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= image_tag @product.image %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!-- <% @title = '実験アプリ' %> -->
<% provide :title, "実験アプリ" %>

<div class="products-index-wrapper">


  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Sample2</a>
      </div>
      <div class="collapse navbar-collapse" id="navbarEexample1">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "#{current_user.id}さん", '#' %></li>
            <li><%= link_to 'アカウント情報を変更', edit_user_registration_path %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'ログイン・サインアップ', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>


  <div class="jumbotron-section">
    <div class="jumbotron jumbotron-main">
    </div>
  </div>


  <div class="application-title section-interval">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1><%= @title %></h1>
        </div>
      </div>
    </div>
  </div>


  <div class="application-record section-interval section-position">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>やったこと</h2>
          <p>GitHubのWikiに書いてあります</p>
        </div>
      </div>
    </div>
  </div>


  <div class="section-interval section-position">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>ユーザ情報</h2>
          <p><%= request.remote_ip %></p>
          <p><%= request.user_agent %></p>
        </div>
      </div>
    </div>
  </div>


  <div class="application-function section-interval section-position">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>ScaffoldでProductの作成機能を追加した</h2>
          <%= link_to 'Productを作成する', new_product_path, class: "btn btn-primary btn-application-function" %>
          <table class="table-products">
            <thead>
              <tr>
                <th>User</th>
                <th>Name</th>
                <th>Url</th>
                <th>Url</th>
                <th>Title</th>
                <th>Content</th>
                <th>Image</th>
                <th>PictureUrl</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @products.each do |product| %>
              <tr>
                <td><%= product.user_id %></td>
                <td><%= product.name %></td>
                <td><%= product.site_url %></td>
                <td class="btn btn-info"><%= link_to '続きを見る', "#{product.site_url}", target: 'blank' %></td>
                <td><%= product.title %></td>
                <td><%= product.content %></td>
                <td><%= image_tag product.image %></td>
                <% if product.picture_url == nil %>
                  <td> <%= image_tag 'no_image.png', class: 'picture-display' %> </td>
                <% else %>
                  <td><%= image_tag product.picture_url, class: 'picture-display' %></td>
                <% end %>
                <td><%= link_to 'Show', product %></td>
                <td><%= link_to 'Edit', edit_product_path(product) %></td>
                <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>


  <div class="application-access-map section-interval section-position">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>地図を中央寄せで埋め込んでみた</h2>
        </div>
        <div class="row">
          <div class="access-map-wrapper">
            <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2">
              <div class="access-map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d205729.03185242313!2d137.10546131074352!3d36.324039223289645!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5ff80862ab1514a5%3A0x767c6bf151a56733!2z5bKQ6Zic55yM6aOb6aio5biC!5e0!3m2!1sja!2sjp!4v1479023235498" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="flex-section section-interval section-position">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>Flexboxを使ってみた-1</h2>
          <div class="flex-sample">
            <div class="flex-item item1"></div>
            <div class="flex-item item2"></div>
            <div class="flex-item item3"></div>
          </div>
          <h2>Flexboxを使ってみた-2</h2>
          <div class="flex-sample">
            <div>
              <%= image_tag 'flex-sample.png', class: 'flex-image' %>
            </div>
            <div class="between-block"></div>
            <div>
              <%= image_tag 'flex-sample.png', class: 'flex-image' %>
            </div>
          </div>
          <h2>Flexboxを使ってみた-3</h2>
          <div class="flex-sample">
            <div>
              <%= image_tag 'flex-sample.png', class: 'flex-image' %>
            </div>
            <div class="red-box-block">
              <div class="red-box">
              </div>
            </div>
            <div>
              <%= image_tag 'flex-sample.png', class: 'flex-image' %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <h2>Flexboxを使ってみた-4</h2>
    </div>
    <div class="tel-section">
      <div class="row">
        <div class="col-md-12">
          <div class="tel-section-flex">
            <p>導入でご不明な点はお気軽にお電話ください</p>
            <p class="text-tel">00-0000-0000</p>
            <p>受付時間 09:00 ~ 17:00（土・日・祝を除きます）</p>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="switch-button-section section-interval section-position">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>ボタンをクリックしたら表示が切り替わる</h2>
          <div class="btn-block">
            <div class="btn btn-primary" id="btn-switch-before">
              <span>Beforeを見る</span>
            </div>
            <div class="btn btn-primary" id="btn-switch-after">
              <span>Afterを見る</span>
            </div>
            <div class="btn btn-primary" id="btn-switch-none">
              <span>何も表示しない</span>
            </div>
          </div>
          <div class="img-block">
            <%= image_tag 'before.png', class: 'img-before' %>
            <%= image_tag 'after.png', class: 'img-after' %>
          </div>
        </div>
      </div>
    </div>
  </div>


    <div class="withdrawal-section section-interval section-position">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>退会用のアンケート</h2>
              <%= link_to 'アンケートに回答する', new_withdrawal_path, class: "btn btn-primary btn-application-function" %>
          </div>
        </div>
      </div>
    </div>


    <div class="click-order-section section-interval section-position">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>クリックされた順番で順位をつける</h2>
            <div class="btn-block">
              <div class="btn btn-primary click-order first second third unclicked" id="first">
                <span>ミスチル</span>
              </div>
              <div class="btn btn-primary click-order first second third unclicked"  id="second">
                <span>アジカン</span>
              </div>
              <div class="btn btn-primary click-order first second third unclicked" id="third">
                <span>リップスライム</span>
              </div>
              <div class="btn btn-warning redo">
                <span>やり直す</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="confirm-click-event-section section-interval section-position">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>removeClassを実行後のclickイベントの挙動について確認</h2>
            <% 8.times.each do |num| %>
              <div class="btn-block" id="block-<%= num + 1 %>">
                <h3><%= num + 1 %>ブロック</h3>
                  <div class="btn btn-primary one two three" id="q<%= 1 + ( 3 * num) %>">
                    <span>ボタンA</span>
                  </div>
                  <div class="btn btn-primary one two three" id="q<%= 2 + ( 3 * num) %>">
                    <span>ボタンB</span>
                  </div>
                  <div class="btn btn-primary one two three" id="q<%= 3 + ( 3 * num) %>">
                    <span>ボタンC</span>
                  </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>


   <div class="js-practice-section section-interval section-position">
     <div class="container">
       <div class="row">
         <div class="col-md-12">
           <h2>「jQuery入門道場」の記述を試してみる-1</h2>
           <h3>イベント移譲</h3>
           <ul>
             <li>一郎</li>
             <li>二郎</li>
             <li>三郎</li>
           </ul>
         </div>
       </div>
     </div>
   </div>


    <div class="js-practice-section section-interval section-position">
     <div class="container">
       <div class="row">
         <div class="col-md-12">
           <h2>「jQuery入門道場」の記述を試してみる-2</h2>
           <h3>dataをjsで指定</h3>
           <form>
             <input type="button" id="taro" value="TARO">
             <input type="button" id="jiro" value="JIRO">
           </form>
           <h3>dataをhtmlで指定</h3>
           <form>
             <input type="button" id="sabrou" value="SABUROU" data-name="三郎" data-birth="東京">
             <input type="button" id="shirou" value="SHIROU" data-name="四郎" data-birth="埼玉">
           </form>
           <h3>dataを受け渡す</h3>
           <form>
             <input type="button" id="gorou" data-myname="五朗" value="GOROU">
           </form>
         </div>
       </div>
     </div>
    </div>


    <div class="social_button_section section-interval section-position">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>シェアボタン</h2>
            <%= social_share_button_tag('Sample2', :url => 'https://afternoon-coast-74109.herokuapp.com', :desc => 'popmacの実験アプリです') %>
          </div>
        </div>
      </div>
    </div>


</div>

app/views/products/new.html.erb
<div class="products-new-wrapper">

  <h1>New Product</h1>

  <%= render 'form' %>

  <%= link_to 'Back', products_path %>

</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @product.site_url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @product.content %>
</p>

<div>
  <strong>Image:</strong>
  <%= image_tag  @product.image %>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/withdrawals/create.html.erb
<div class="withdrawals-create-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>回答を受け付けました</h2>
        <%= link_to 'トップへ戻る', root_path %>
      </div>
    </div>
  </div>
</div>

app/views/withdrawals/new.html.erb
<div class="withdrawals-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h1>アンケート</h1>
        <% if @withdrawal.errors.any? %>
        <div id="error_explanation">
          <h2><%= @withdrawal.errors.count %>件のエラーがあります。</h2>

          <ul>
            <% @withdrawal.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <%= form_for @withdrawal do |f| %>
          <div class="form-group">
            <%= f.label :impression, 'このアプリの感想を教えてください。', class: 'enquete-title' %></br>
            <%= hidden_field_tag 'withdrawal[impression]' %>
            <%= f.check_box 'impression_unuseful', {}, checked_value = '1' %>
            <%= f.label :impression_unuseful, '使いにくい' %></br>
            <%= f.check_box 'impression_difficult', {}, checked_value = '1' %>
            <%= f.label :impression_difficult, 'わかりにくい' %></br>
            <%= f.check_box 'impression_not_enough', {}, checked_value = '1' %>
            <%= f.label :impression_not_enough, '機能が少ない' %></br>
          </div>
          <div class="form-group enquete-btn-block">
            <%= f.submit 'アンケートに答えて退会を申請する', class: 'btn btn-primary btn-enquete' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>